#@data/values

#@overlay/match-child-defaults missing_ok=True
---
buildService:
  version: "1.9.0"

tap:
  version: "1.4.0"
  namespace: tap-install
  devNamespace: development

  catalogs:
  - https://github.com/pacphi/tap-gui-catalog/blob/main/catalog-info.yaml

  cluster:
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-contour-cluster-issuer

  #! Uncomment all lines below if installing TAP on AWS
  #! contour:
  #!   infrastructure_provider: aws
  #!   envoy:
  #!     service:
  #!       aws:
  #!         LBType: nlb

  registry:
    repositories:
      buildService: tanzu/build-service
      ootbSupplyChain: tanzu/supply-chain

  domains:
    main: tap.tanzu.corp
    tapGui: tap-gui.tap.tanzu.corp
    learningCenter: learningcenter.tanzu.corp
    knative: tanzu.corp

  ingress:
    contour_tls_secret: tls
    contour_tls_namespace: contour-tls

  #! Change to "jammy-only" if you want to install Tanzu Application Platform with Ubuntu 22.04 (Jammy) as the only available stack
  stack_configuration: "default"

  supply_chain:
    #! cluster_builder: full
    #! choices below are: [ go-git, libgit2 ]
    git_implementation: go-git
    gitops:
      enabled: "false"
      provider: github.com
      repository:
        owner: change_me
        name: tap-gitops-depot
        branch: main
      #! choices below are: [ "", git-http, git-ssh ]
      #! if you set git-http or git-ssh then all Git repos will be authenticated using credentials
      #! in k8s secrets of the same name in a developer namespace
      ssh_secret: ""
